### ISSUE TITLE
Can I add api ?

### ISSUE THREAD

**Issue by MohamedAliHamza** [MVCBlogs/blog-mvc-django#1]
I'm interested to build api using django rest framework.

**Comment by danielgara** [comment]
Hi @MohamedAliHamza, do you refer to add an API section to the current blog-mvc-django project?

If that's the case, we suggest you to do it over a new project. Because we are using these projects to make a comparison between only MVC applications.

Let us know if you implement it to take a look of it. Thanks.

**Comment by MohamedAliHamza** [comment]
> Hi @MohamedAliHamza, do you refer to add an API section to the current blog-mvc-django project?
> 
> If that's the case, we suggest you to do it over a new project. Because we are using these projects to make a comparison between only MVC applications.
> 
> Let us know if you implement it to take a look of it. Thanks.
